// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Spaceific.Api.Services;

#nullable disable

namespace Spaceific.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260212115529_AddUsersTable")]
    partial class AddUsersTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Spaceific.Api.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllDay")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("End")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Room")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AllDay = false,
                            CreatedAt = new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2026, 2, 7, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Andi",
                            IsDeleted = false,
                            LastName = "Pratama",
                            Purpose = "Rapat divisi IT",
                            Room = "HH-203",
                            Start = new DateTime(2026, 2, 7, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Pending",
                            UpdatedAt = new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            AllDay = false,
                            CreatedAt = new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2026, 2, 8, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Siti",
                            IsDeleted = false,
                            LastName = "Aisyah",
                            Purpose = "Presentasi proyek PBL",
                            Room = "B-304",
                            Start = new DateTime(2026, 2, 8, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Approved",
                            UpdatedAt = new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            AllDay = false,
                            CreatedAt = new DateTime(2026, 2, 7, 13, 47, 18, 0, DateTimeKind.Unspecified),
                            End = new DateTime(2026, 2, 10, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Rina",
                            IsDeleted = false,
                            LastName = "Kusuma",
                            Purpose = "Pelatihan editing video",
                            Room = "SAW-0608",
                            Start = new DateTime(2026, 2, 10, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Rejected",
                            UpdatedAt = new DateTime(2026, 2, 7, 13, 47, 18, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Spaceific.Api.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Building")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Building = "D4",
                            Capacity = 30,
                            CreatedAt = new DateTime(2026, 2, 11, 22, 52, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "B-102",
                            UpdatedAt = new DateTime(2026, 2, 11, 22, 52, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Building = "D3",
                            Capacity = 30,
                            CreatedAt = new DateTime(2026, 2, 11, 22, 52, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "HH-103",
                            UpdatedAt = new DateTime(2026, 2, 11, 22, 52, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Building = "SAW",
                            Capacity = 100,
                            CreatedAt = new DateTime(2026, 2, 11, 22, 52, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "SAW-0201",
                            UpdatedAt = new DateTime(2026, 2, 11, 22, 52, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Building = "Pascasarjana",
                            Capacity = 50,
                            CreatedAt = new DateTime(2026, 2, 11, 22, 52, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "PS-0105",
                            UpdatedAt = new DateTime(2026, 2, 11, 22, 52, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Spaceific.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
